### ISSUE TITLE
Slider resize doesn't work -> only container with slider is resized.

### ISSUE THREAD

**Issue by wszczepanski97** [Samsung/TAU-Design-Editor#238] opened 2019-07-25 15:28 UTC
## Technical
Platform: WATT/VSC,
Profile: only Mobile 
## Description
Slider component resize doesn't work and in preview mode it looks strange
## Steps to reproduce
1. Create a new project in Design Editor
2. d&d slider to template.
3. Resize slider to be bigger/smaller
## Expected behaviour
All parts of slider are resized.
## Actual behaviour
Only gray part of slider changed its size.

**Comment by lslachciak** [comment] 2019-07-29 06:49
@wszczepanski97 please specify platform for issue: wearable? mobile?

**Comment by lslachciak** [comment] 2019-08-02 12:36
@wszczepanski97 this issue was fixed?

**Comment by wszczepanski97** [comment] 2019-08-02 12:59
@lslachciak problem still exists, slider is not resized correctly.

**Comment by lslachciak** [comment] 2019-08-02 13:18
Duplicate of https://github.com/Samsung/TAU-Design-Editor/issues/244

**Closed by lslachciak** 2019-08-02 13:18 UTC
Labels: 1.0, bug
