### ISSUE TITLE
[VSC][Wearable] Slider doesn't look like it should

### ISSUE THREAD

**Issue by wszczepanski97** [Samsung/TAU-Design-Editor#291] opened 2019-08-22 12:17 UTC
## Technical
only VSC
## Description
Slider is not looking good. Problem appears only in VSC.
## Steps to reproduce
1. Create a new project in Design Editor
2. Drag&Drop slider to template.
## Expected behaviour
Slider should look like this.
![wattslider](https://user-images.githubusercontent.com/31214439/63513794-6dcaaf80-c4e7-11e9-9922-1e74887df51b.png)

## Actual behaviour
Now slider look like this
![sliderlook](https://user-images.githubusercontent.com/31214439/63513827-80dd7f80-c4e7-11e9-904a-53df3ede1a98.png)

**Comment by singa2000** [comment] 2019-08-22 13:42
It  is  different if  it use TAU 1.1 library  or  not.
If  it  use  TAU  1.1.3 , it is good.
But it is TAU  1.0, it  have  the  issue.
WATT  use the  TAU  1.1

**Comment by korneliakobiela** [comment] 2019-09-02 10:51
I cannot reproduce this issue in any way with the newest code and new templates. So I close it

**Closed by korneliakobiela** 2019-09-02 10:51 UTC
Labels: bug, important, in progress, vscode, vscode-verification, wearable
